#####################################
### FONDO ###
#####################################
background {
    monitor =
    path = /home/edk367/Pictures/Wallpapers/fern-wallpaper.jpeg
    blur_passes = 1
    blur_size = 2
    contrast = 0.9
    brightness = 0.75
    vibrancy = 0.2
    vibrancy_darkness = 0.0
}

#####################################
### GENERAL ###
#####################################
general {
    no_fade_in = false
    no_fade_out = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = false
}

#####################################
### HORA ###
#####################################
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(205, 214, 244, 0.95)
    font_size = 95
    font_family = JetBrainsMono Nerd Font
    position = 0, 250
    halign = center
    valign = center
}

#####################################
### FECHA ###
#####################################
label {
    monitor =
    text = cmd[update:60000] echo "$(date +'%A, %d de %B')"
    color = rgba(205, 214, 244, 0.75)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

#####################################
### FOTO DE PERFIL ###
#####################################
image {
    monitor =
    path = /home/edk367/.config/hypr/user.png
    border_size = 5
    border_color = rgba(205, 214, 244, 0.9)
    size = 150
    rounding = -1
    rotate = 0
    reload_time = -1
    position = 0, 40
    halign = center
    valign = center
}

#####################################
### SALUDO ###
#####################################
label {
    monitor =
    text = Porque para mí el vivir es Cristo, y el morir es ganancia.
    color = rgba(205, 214, 244, 0.9)
    font_size = 27
    font_family = JetBrainsMono Nerd Font
    position = 0, -80
    halign = center
    valign = center
}


#####################################
### USUARIO (texto encima del campo) ###
#####################################
label {
    monitor =
    text =  $USER
    color = rgba(205, 214, 244, 0.85)
    font_size = 25
    font_family = JetBrainsMono Nerd Font
    position = 0, -150
    halign = center
    valign = center
}
#####################################
### CAJA DE FONDO DEL CAMPO DE TEXTO ###
#####################################
input-field {
    monitor =
    size = 280, 50
    position = 0, -225
    halign = center
    valign = center
    outline_thickness = 5
    rounding = 15
    outer_color = rgba(94e2d5ff) rgba(b4a0f5ff) rgba(f5c2e7ff) 0deg
    inner_color = rgba(1e1e2ecc)
    font_color = rgba(cdd6f4ff)
    check_color = rgba(a6e3a1ff) rgba(94e2d5ff) 0deg
    fail_color = rgba(f38ba8ff) rgba(b4a0f5ff) 0deg
    font_family = JetBrainsMono Nerd Font
    font_size = 22
    placeholder_text = <i><span foreground="##94e2d5">Enter your password</span></i>
    fail_text = <i><span foreground="##f38ba8">Incorrect password</span> <b>($ATTEMPTS)</b></i>
    fail_timeout = 1700
    fail_transition = 300
    hide_input = false
    fade_on_empty = false
    dots_size = 0.35
    dots_spacing = 0.3
    dots_center = true
    dots_rounding = -1
    capslock_color = rgba(f9e2afff)
    numlock_color = rgba(89b4faff)
    bothlock_color = rgba(fab387ff)
    invert_numlock = false
    swap_font_color = false
    shadow_passes = 3
    shadow_size = 5
    shadow_color = rgba(00000099)
    shadow_boost = 1.2
}
