# =====================================
# AUDIO (PipeWire)
# =====================================
exec-once = systemctl --user unmask pipewire pipewire-pulse wireplumber
exec-once = systemctl --user start pipewire pipewire-pulse wireplumber

