# =====================================
# HYPRLAND CONFIG - ARCHIVO PRINCIPAL
# =====================================

# Importar todas las configuraciones
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/startup.conf
source = ~/.config/hypr/audio.conf
source = ~/.config/hypr/portals.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/dwindle.conf
source = ~/.config/hypr/gestures.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/misc.conf
source = ~/.config/hypr/keybindings.conf
