# =====================================
# TECLAS (keybindings)
# =====================================
$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = wofi --show drun

# Lanzadores
bind = $mainMod, $mainMod, exec, $menu
bind = $mainMod, Return, exec, $terminal
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, Space, exec, pkill rofi || ~/.config/rofi/scripts/launcher_t6

# Control de ventanas
bind = $mainMod, Q, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, B, exec, ~/.config/hypr/scripts/send-back.sh
bind = $mainMod, P, pseudo,
bind = $mainMod, J, layoutmsg, togglesplit
bind = $mainMod, F, fullscreen,

# Navegación
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

# Workspaces
bind = $mainMod, 1, movetoworkspace, 1
bind = $mainMod, 2, movetoworkspace, 2
bind = $mainMod, 3, movetoworkspace, 3
bind = $mainMod, 4, movetoworkspace, 4
bind = $mainMod, 5, movetoworkspace, 5
bind = $mainMod, 6, movetoworkspace, 6
bind = $mainMod, 7, movetoworkspace, 7
bind = $mainMod, 8, movetoworkspace, 8
bind = $mainMod, 9, movetoworkspace, 9
bind = $mainMod, 0, movetoworkspace, 10

# Movimiento con mouse
bindm = SHIFT, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# Sistema
bind = $mainMod, M, exit,
bind = $mainMod SHIFT, L, exec, hyprlock
bind = $mainMod, Print, exec, flameshot gui

# Noctalia
bind = $mainMod, S, exec, noctalia msg panel-toggle control-center
bind = $mainMod, G, exec, noctalia msg panel-toggle control-center media
bind = $mainMod, comma, exec, noctalia msg settings-toggle

# Multimedia
bind = , XF86AudioRaiseVolume, exec, noctalia msg volume-up
bind = , XF86AudioLowerVolume, exec, noctalia msg volume-down
bind = , XF86AudioMute, exec, noctalia msg volume-mute
bind = , XF86MonBrightnessUp, exec, noctalia msg brightness-up
bind = , XF86MonBrightnessDown, exec, noctalia msg brightness-down

