# =====================================
# MISCELÁNEA
# =====================================
misc {
    disable_hyprland_logo = true
    focus_on_activate = false
    force_default_wallpaper = 0
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
}

workspace = special, persistent:true
