# =====================================
# PORTALES PARA CAPTURA
# =====================================
exec-once = systemctl --user stop xdg-desktop-portal
exec-once = systemctl --user stop xdg-desktop-portal-hyprland
exec-once = systemctl --user start xdg-desktop-portal-gtk
exec-once = sleep 1 && systemctl --user start xdg-desktop-portal-hyprland
exec-once = sleep 2 && systemctl --user start xdg-desktop-portal

