# =====================================
# PROGRAMAS AL INICIO
# =====================================
exec-once = noctalia --daemon
# exec-once = waybar
# exec-once = dunst
exec-once = hyprpaper
exec-once = /usr/libexec/polkit-gnome-authentication-agent-1
exec-once = nm-applet --indicator
exec-once = hypridle
exec-once = hyprsunset
