# =====================================
# REGLAS DE VENTANAS
# =====================================
# windowrule = match:class .*, suppress_event maximize
windowrule = match:class .*, float 1
windowrule = match:class ^(pavucontrol)$, size (monitor_w*0.6) (monitor_h*0.7)

